### ISSUE TITLE
When I'm running the "model_ test. py" file ,The following error occurs in the file "tag_list=runtagger_parse (total_sen)". Is it related to ark tweet-nlp-0.3.2. jar? How can I solve it?

### ISSUE THREAD

**Issue by CTGUzhangguangyi** [uhuohuy/GazPNE#5]
Traceback (most recent call last):
  File "D:/Yvonne/yan_1/before/studio/learning_assignment/assigment_1/daima/GazPNE-master/model_test.py", line 565, in <module>
    main()
  File "D:/Yvonne/yan_1/before/studio/learning_assignment/assigment_1/daima/GazPNE-master/model_test.py", line 390, in main
    tag_list = runtagger_parse(total_sen)
  File "D:\Yvonne\yan_1\before\studio\learning_assignment\assigment_1\daima\GazPNE-master\CMUTweetTagger.py", line 74, in runtagger_parse
    pos_raw_results = _call_runtagger(tweets, run_tagger_cmd)
  File "D:\Yvonne\yan_1\before\studio\learning_assignment\assigment_1\daima\GazPNE-master\CMUTweetTagger.py", line 56, in _call_runtagger
    po = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "E:\Miniconda\Miniconda3-py37\envs\GazPNE-master\lib\subprocess.py", line 801, in __init__
    restore_signals, start_new_session)
  File "E:\Miniconda\Miniconda3-py37\envs\GazPNE-master\lib\subprocess.py", line 1208, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by xukehu** [comment]
Yes. The error is related to tweet-nlp-0.3.2. jar. Have you installed Java on your machine? Or you can re-download tweet-nlp-0.3.2. jar from other sources.
